d1=input('Digite algo: ')
f1=type(d1)
n1=d1.isnumeric()
a1=d1.isalpha()
b1=d1.isupper()
print('O tipo primitivo do valor digitado é {} '.format(f1))
print('O valor digitado é numérico? {}'.format(n1))
print('O valor digitado é alfabético? {}'.format(a1))
print('O valor digitado está em letras maiusculas? {}'.format(b1))
